spring.application.name=MiniInventario
server.port=8084

# Configuración de Conexión Corregida
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=W2QMEGa89MAxqeK2OcPIyOmefPxonW
# Cambiado aquí: Añadido el protocolo completo jdbc, host y puerto
spring.datasource.url=jdbc:postgresql://us-east-1.7ce1a182-dbb0-45a7-992b-082a28cb6f85.aws.yugabyte.cloud:5433/yugabyte
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

#Documentación
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/documentacion/swagger-ui.html
springdoc.paths-to-match=/api/v1/categorias/**, /api/v1/productos/**
# Le dice a Swagger en qué paquete buscar tus @RestController
springdoc.packages-to-scan=com.ipn.mx.miniinventario.features

#htpp://localhost:8084/documentacion/swagger-ui.html
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=monsecontreras216@gmail.com
spring.mail.password=qqrq iwyr rduz fwss